import { Product } from './types/Product'

export const mensShirts: Product[] = [
  {
    name: 'YO Slim shirt',
    slug: 'yo-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-1.jpg',
    price: 80,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'best shirt',
  },
  {
    name: 'OX Slim shirt',
    slug: 'ox-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-2.jpg',
    price: 120,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'OX',
    rating: 4.0,
    numReviews: 0,
    description: 'medium quality shirt',
  },
  {
    name: 'YM Slim shirt',
    slug: 'ym-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-3.jpg',
    price: 90,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 0,
    brand: 'YM',
    rating: 3.5,
    numReviews: 0,
    description: 'perfekt shirt',
  },
  {
    name: 'XM Slim shirt',
    slug: 'xm-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-4.jpg',
    price: 115,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 3,
    brand: 'XM',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality shirt',
  },
  {
    name: 'OO Slim shirt',
    slug: 'oo-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-5.jpg',
    price: 100,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 2,
    brand: 'OX',
    rating: 3.0,
    numReviews: 0,
    description: 'simply good shirt',
  },
]

export const mensSweaters: Product[] = [
  {
    name: 'YO Slim sweater',
    slug: 'yo-slim-sweater',
    category: 'Sweaters',
    subcategory: 'mens',
    image: '../images/men/sweaters/sweater-1.jpg',
    price: 80,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'simply good sweater',
  },
  {
    name: 'OX Slim sweater',
    slug: 'ox-slim-shisweaterrt',
    category: 'Sweaters',
    subcategory: 'mens',
    image: '../images/men/sweaters/sweater-2.jpg',
    price: 120,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'OX',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality sweater',
  },
  {
    name: 'YM Slim sweater',
    slug: 'ym-slim-sweater',
    category: 'Sweaters',
    subcategory: 'mens',
    image: '../images/men/sweaters/sweater-3.jpg',
    price: 90,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 0,
    brand: 'YM',
    rating: 3.5,
    numReviews: 0,
    description: 'perfekt sweater',
  },
  {
    name: 'XM Slim sweater',
    slug: 'xm-slim-sweater',
    category: 'Sweaters',
    subcategory: 'mens',
    image: '../images/men/sweaters/sweater-4.jpg',
    price: 115,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 3,
    brand: 'XM',
    rating: 4.0,
    numReviews: 0,
    description: 'best sweater',
  },
  {
    name: 'OO Slim sweater',
    slug: 'oo-slim-sweater',
    category: 'Sweaters',
    subcategory: 'mens',
    image: '../images/men/sweaters/sweater-5.jpg',
    price: 100,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 2,
    brand: 'OX',
    rating: 3.0,
    numReviews: 0,
    description: 'most popular sweater',
  },
]

export const mensTrousers: Product[] = [
  {
    name: 'YO Slim trouser',
    slug: 'yo-slim-trouser',
    category: 'Trousers',
    subcategory: 'mens',
    image: '../images/men/trousers/trousers-1.jpg',
    price: 80,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'simply good trousers',
  },
  {
    name: 'OX Slim trousers',
    slug: 'ox-slim-trousers',
    category: 'Trousers',
    subcategory: 'mens',
    image: '../images/men/trousers/trousers-2.jpg',
    price: 120,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'OX',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality trousers',
  },
  {
    name: 'YM Slim trousers',
    slug: 'ym-slim-trousers',
    category: 'Trousers',
    subcategory: 'mens',
    image: '../images/men/trousers/trousers-3.jpg',
    price: 90,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 0,
    brand: 'YM',
    rating: 3.5,
    numReviews: 0,
    description: 'perfekt trousers',
  },
  {
    name: 'XM Slim trousers',
    slug: 'xm-slim-trousers',
    category: 'Trousers',
    subcategory: 'mens',
    image: '../images/men/trousers/trousers-4.jpg',
    price: 115,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 3,
    brand: 'XM',
    rating: 4.0,
    numReviews: 0,
    description: 'best trousers',
  },
  {
    name: 'OO Slim trousers',
    slug: 'oo-slim-trousers',
    category: 'Trousers',
    subcategory: 'mens',
    image: '../images/men/trousers/trousers-5.jpg',
    price: 100,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 2,
    brand: 'OX',
    rating: 3.0,
    numReviews: 0,
    description: 'most popular trousers',
  },
]

export const womensShirts: Product[] = [
  {
    name: 'YO Slim shirt',
    slug: 'yo-slim-shirt',
    category: 'Shirts',
    subcategory: 'women',
    image: '../images/women/t-shirts/t-shirt-1.jpg',
    price: 80,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'best shirt',
  },
  {
    name: 'OX Slim shirt',
    slug: 'ox-slim-shirt',
    category: 'Shirts',
    subcategory: 'women',
    image: '../images/women/t-shirts/t-shirt-2.jpg',
    price: 120,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'OX',
    rating: 4.0,
    numReviews: 0,
    description: 'medium quality shirt',
  },
  {
    name: 'YM Slim shirt',
    slug: 'ym-slim-shirt',
    category: 'Shirts',
    subcategory: 'women',
    image: '../images/women/t-shirts/t-shirt-3.jpg',
    price: 90,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 0,
    brand: 'YM',
    rating: 3.5,
    numReviews: 0,
    description: 'perfekt shirt',
  },
  {
    name: 'XM Slim shirt',
    slug: 'xm-slim-shirt',
    category: 'Shirts',
    subcategory: 'women',
    image: '../images/women/t-shirts/t-shirt-4.jpg',
    price: 115,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 3,
    brand: 'XM',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality shirt',
  },
  {
    name: 'OO Slim shirt',
    slug: 'oo-slim-shirt',
    category: 'Shirts',
    subcategory: 'women',
    image: '../images/women/t-shirts/t-shirt-5.jpg',
    price: 100,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 2,
    brand: 'OX',
    rating: 3.0,
    numReviews: 0,
    description: 'simply good shirt',
  },
]

export const womensSweaters: Product[] = [
  {
    name: 'YO Slim sweater',
    slug: 'yo-slim-sweater',
    category: 'Sweaters',
    subcategory: 'women',
    image: '../images/women/sweaters/sweater-1.jpg',
    price: 80,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'simply good sweater',
  },
  {
    name: 'OX Slim sweater',
    slug: 'ox-slim-shisweaterrt',
    category: 'Sweaters',
    subcategory: 'women',
    image: '../images/women/sweaters/sweater-2.jpg',
    price: 120,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'OX',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality sweater',
  },
  {
    name: 'YM Slim sweater',
    slug: 'ym-slim-sweater',
    category: 'Sweaters',
    subcategory: 'women',
    image: '../images/women/sweaters/sweater-3.jpg',
    price: 90,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 0,
    brand: 'YM',
    rating: 3.5,
    numReviews: 0,
    description: 'perfekt sweater',
  },
  {
    name: 'XM Slim sweater',
    slug: 'xm-slim-sweater',
    category: 'Sweaters',
    subcategory: 'women',
    image: '../images/women/sweaters/sweater-4.jpg',
    price: 115,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 3,
    brand: 'XM',
    rating: 4.0,
    numReviews: 0,
    description: 'best sweater',
  },
  {
    name: 'OO Slim sweater',
    slug: 'oo-slim-sweater',
    category: 'Sweaters',
    subcategory: 'women',
    image: '../images/women/sweaters/sweater-5.jpg',
    price: 100,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 2,
    brand: 'OX',
    rating: 3.0,
    numReviews: 0,
    description: 'most popular sweater',
  },
]

export const womenBlouses: Product[] = [
  {
    name: 'YO Slim blouse',
    slug: 'yo-slim-blouse',
    category: 'Blouses',
    subcategory: 'women',
    image: '../images/women/blouses/blouse-1.jpg',
    price: 80,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'simply good blouse',
  },
  {
    name: 'OX Slim trousers',
    slug: 'ox-slim-trousers',
    category: 'Blouses',
    subcategory: 'women',
    image: '../images/women/blouses/blouse-2.jpg',
    price: 120,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 10,
    brand: 'OX',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality blouse',
  },
  {
    name: 'YM Slim blouse',
    slug: 'ym-slim-blouse',
    category: 'Blouses',
    subcategory: 'women',
    image: '../images/women/blouses/blouse-3.jpg',
    price: 90,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 0,
    brand: 'YM',
    rating: 3.5,
    numReviews: 0,
    description: 'perfekt blouse',
  },
  {
    name: 'XM Slim blouse',
    slug: 'xm-slim-blouse',
    category: 'Blouses',
    subcategory: 'women',
    image: '../images/women/blouses/blouse-4.jpg',
    price: 115,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 3,
    brand: 'XM',
    rating: 4.0,
    numReviews: 0,
    description: 'best blouse',
  },
  {
    name: 'OO Slim blouse',
    slug: 'oo-slim-blouse',
    category: 'Blouses',
    subcategory: 'women',
    image: '../images/women/blouses/blouse-5.jpg',
    price: 100,
    discount: 0,
    discount_start: undefined,
    discount_end: undefined,
    countInStock: 2,
    brand: 'OX',
    rating: 3.0,
    numReviews: 0,
    description: 'most popular blouse',
  },
]

export const sampleProducts: Product[][] = [mensShirts, mensSweaters, mensTrousers, womensShirts, womensSweaters, womenBlouses]
  // {
  //   name: 'YO Slim shirt',
  //   slug: 'yo-slim-shirt',
  //   category: 'Shirts',
  //   subcategory: 'mens',
  //   image: '../images/men/t-shirts/t-shirt-1',
  //   price: 80,
  //   countInStock: 10,
  //   brand: 'YO',
  //   rating: 4.5,
  //   numReviews: 0,
  //   description: 'high quality shirt',
  // },
  // {
  //   name: 'Adidas Fit Shirt',
  //   slug: 'adidas-fit-shirt',
  //   category: 'Shirts',
  //   image: '../images/p2.jpg',
  //   price: 100,
  //   countInStock: 20,
  //   brand: 'Adidas',
  //   rating: 4.0,
  //   numReviews: 10,
  //   description: 'high quality product',
  // },
  // {
  //   name: 'Lacoste Free Pants',
  //   slug: 'lacoste-free-pants',
  //   category: 'Pants',
  //   image: '../images/p3.jpg',
  //   price: 220,
  //   countInStock: 0,
  //   brand: 'Lacoste',
  //   rating: 4.8,
  //   numReviews: 17,
  //   description: 'high quality product',
  // },
  // {
  //   name: 'Nike Slim Pant',
  //   slug: 'nike-slim-pant',
  //   category: 'Pants',
  //   image: '../images/p4.jpg',
  //   price: 78,
  //   countInStock: 15,
  //   brand: 'Nike',
  //   rating: 4.5,
  //   numReviews: 14,
  //   description: 'high quality product',
  // },
