import { Product } from './types/Product'

export const mensShirts: Product[] = [
  {
    name: 'YO Slim shirt',
    slug: 'yo-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-1',
    price: 80,
    discount: 0,
    discount_period: undefined,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'high quality shirt',
  },
  {
    name: 'OX Slim shirt',
    slug: 'ox-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-2',
    price: 120,
    discount: 0,
    discount_period: undefined,
    countInStock: 10,
    brand: 'OX',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality shirt',
  },
  {
    name: 'YM Slim shirt',
    slug: 'ym-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-3',
    price: 90,
    discount: 0,
    discount_period: undefined,
    countInStock: 0,
    brand: 'YM',
    rating: 3.5,
    numReviews: 0,
    description: 'high quality shirt',
  },
  {
    name: 'XM Slim shirt',
    slug: 'xm-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-4',
    price: 115,
    discount: 0,
    discount_period: undefined,
    countInStock: 3,
    brand: 'XM',
    rating: 4.0,
    numReviews: 0,
    description: 'high quality shirt',
  },
  {
    name: 'OO Slim shirt',
    slug: 'oo-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-5',
    price: 100,
    discount: 0,
    discount_period: undefined,
    countInStock: 2,
    brand: 'OX',
    rating: 3.0,
    numReviews: 0,
    description: 'high quality shirt',
  },
]

export const sampleProducts: Product[] = [
  {
    name: 'YO Slim shirt',
    slug: 'yo-slim-shirt',
    category: 'Shirts',
    subcategory: 'mens',
    image: '../images/men/t-shirts/t-shirt-1',
    price: 80,
    countInStock: 10,
    brand: 'YO',
    rating: 4.5,
    numReviews: 0,
    description: 'high quality shirt',
  },
  // {
  //   name: 'Adidas Fit Shirt',
  //   slug: 'adidas-fit-shirt',
  //   category: 'Shirts',
  //   image: '../images/p2.jpg',
  //   price: 100,
  //   countInStock: 20,
  //   brand: 'Adidas',
  //   rating: 4.0,
  //   numReviews: 10,
  //   description: 'high quality product',
  // },
  // {
  //   name: 'Lacoste Free Pants',
  //   slug: 'lacoste-free-pants',
  //   category: 'Pants',
  //   image: '../images/p3.jpg',
  //   price: 220,
  //   countInStock: 0,
  //   brand: 'Lacoste',
  //   rating: 4.8,
  //   numReviews: 17,
  //   description: 'high quality product',
  // },
  // {
  //   name: 'Nike Slim Pant',
  //   slug: 'nike-slim-pant',
  //   category: 'Pants',
  //   image: '../images/p4.jpg',
  //   price: 78,
  //   countInStock: 15,
  //   brand: 'Nike',
  //   rating: 4.5,
  //   numReviews: 14,
  //   description: 'high quality product',
  // },
]